name: Build and test on pull-request

on:
  pull_request:
    branches:
      - main

jobs:

  build:
    environment: CI/CD

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ubuntu dependency
        run: |
          sudo apt-get install libportaudio2 -y

      - name: Install module
        run: |
          pip install --no-cache-dir build setuptools wheel
          pip install --no-cache-dir -e .[dev]

      - name: build wheel
        run: |
          python -m build --wheel --outdir dist/ .
